"""Add subscription tier with default

Revision ID: 527e31d3d9ae
Revises: b3f18d046a35
Create Date: 2025-09-12 18:27:23.989269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527e31d3d9ae'
down_revision = 'b3f18d046a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=50), server_default='trial', nullable=False))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
